settings:

  start_year: 1990
  end_year: 2020
  crop_x_index: [116,276]
  crop_y_index: [40,200]
  is_longitude_centered: false  # set to false if your data's longitude range is [0, 360), true if [-180, 180)
  overwinter: true
  chunks: "auto"
  parallel: true
  n_cpu_cores: 19
  path_to_cffdrs-ng: "/path/to/cffdrs-ng"
  output_dir: "/path/to/output"
  output_vars: ["MASK", "FFMC", "DMC", "DC", "ISI", "BUI", "FWI"]
  output_in_batches: true  # set to true if your domain is large (the batches will be combined into a single file anyways)

calculation_parameters:

  FFMC_default: 85.0
  DMC_default: 6.0
  DC_default: 15.0
  season_consecutive_days: 3
  season_start_temp: 12.0
  season_stop_temp: 5.0
  carry_over_fraction: 1.0
  wetting_efficiency_fraction: 0.75

# Note: all data must have identical dimensions, as well as have
# both latitude and longitude as a data variable!
data_vars:

  t_dim_name: "time"
  x_dim_name: "longitude"
  y_dim_name: "latitude"
  lon_coord_name: "longitude"
  lat_coord_name: "latitude"

  wind_speed:

    alternative_names: ['WS10', 'WindSpeed', 'WindSpeed10m','WS','ws','ws10','sfcWind','SFCWIND']
    description: "Wind speed in km/h"
    path: "/path/to/winds.nc"
    transform: "x * 3.6"  # can use transform to convert units from m/s to km/h

  air_temperature:

    alternative_names: ['T2', 'Temperature', 'T', 'Temp', 'temp', 'temperature', 'air_temperature', 'TAS', 'tas']
    description: "Air temperature in °C"
    path: "/path/to/air_temperature.nc"
    transform: "x - 273.15"

  relative_humidity:

    alternative_names: ["RH", "RH2", "relative_humidity_2m", "RH2M", "rh", "rh2"]
    description: "Relative humidity in % (0-100)"
    path: "/path/to/relative_humidity.nc"
    transform: null

  precipitation:

    alternative_names: ["Precip", "Pr", "total_precipitation", "PREC", "prec", "pr", "rainfall", "Rainfall"]
    description: "Total accumulated precipitation over the past hour in mm"
    path: "/path/to/precip_accum.nc"
    transform: "x * 1000"

