settings:

  start_year: 2001
  end_year: 2002
  crop_x_index: [116,276]
  crop_y_index: [40,200]
  convert_lon_to_centered: True
  overwinter: true
  chunks: "auto"
  parallel: true
  n_cpu_cores: 19
  path_to_cffdrs-ng: "/users/rpayne/cffdrs-ng"
  output_dir: "/users/rpayne/FWI_test"
  output_vars: ["MASK", "FFMC", "DMC", "DC", "ISI", "BUI", "FWI"]
  output_in_batches: true

calculation_parameters:

  FFMC_default: 85.0
  DMC_default: 6.0
  DC_default: 15.0
  season_consecutive_days: 3
  season_start_temp: 12.0
  season_stop_temp: 5.0
  carry_over_fraction: 1.0
  wetting_efficiency_fraction: 0.75

# Note: all data must have identical dimensions, as well as have
# both latitude and longitude as a data variable!
data_vars:

  t_dim_name: "time"
  x_dim_name: "longitude"
  y_dim_name: "latitude"
  lon_coord_name: "longitude"
  lat_coord_name: "latitude"

  wind_speed:

    alternative_names: ['WS10', 'WindSpeed', 'WindSpeed10m','WS','ws','ws10','sfcWind','SFCWIND']
    description: "Wind speed at 10 meters above ground level (in km/hr)"
    path: "/users/rpayne/data/unproc/ERA5/ALL/sfcWind_1hr_ERA5_an_RDA-025_1979010100-2018123123.nc"
    transform: "x * 3.6"

  air_temperature:

    alternative_names: ['T2', 'Temperature', 'T', 'Temp', 'temp', 'temperature', 'air_temperature', 'TAS', 'tas']
    description: "Air temperature at 2 meters above ground level (in °C)"
    path: "/users/rpayne/data/unproc/ERA5/ALL/tas_1hr_ERA5_an_RDA-025_1979010100-2018123123.nc"
    transform: "x - 273.15"

  relative_humidity:

    alternative_names: ["RH", "RH2", "relative_humidity_2m", "RH2M", "rh", "rh2"]
    description: "Relative humidity at 2 meters above ground level (in %, 0-100)"
    path: "/users/rpayne/data/unproc/ERA5/RH_new/*.nc"
    transform: null

  precipitation:

    alternative_names: ["Precip", "Pr", "total_precipitation", "PREC", "prec", "pr", "rainfall", "Rainfall"]
    description: "Total accumulated precipitation over the past hour (in mm)"
    path: "/users/rpayne/data/unproc/ERA5/PREC_fc/*.nc"
    transform: "x * 1000"

