settings:

  start_year: 2003
  end_year: 2004
  crop_x_index: [128,256]
  crop_y_index: [140,286]
  overwinter: true
  chunks: "auto"
  parallel: true
  n_cpu_cores: 20
  path_to_cffdrs-ng: "/users/rpayne/cffdrs-ng"
  output_dir: "/users/rpayne/FWI_test"
  output_vars: ["season_mask", "FFMC", "DMC", "DC", "ISI", "BUI", "FWI"]

calculation_parameters:

  FFMC_default: 85.0
  DMC_default: 6.0
  DC_default: 15.0
  season_consecutive_days: 3
  season_start_temp: 12.0
  season_stop_temp: 5.0
  carry_over_fraction: 1.0
  wetting_efficiency_fraction: 0.75

# Note: all data must have identical dimensions, as well as have
# both latitude and longitude as a data variable!
data_vars:

  t_dim_name: "time"
  x_dim_name: "rlon"
  y_dim_name: "rlat"

  wind_speed:

    alternative_names: ['WS10', 'WindSpeed', 'WindSpeed10m','WS','ws','ws10']
    description: "Wind speed at 10 meters above ground level"
    path: "/users/rpayne/data/unproc/WRF/ctl/WS10/*.nc"
    transform: null

  air_temperature:

    alternative_names: ['T2', 'Temperature', 'T', 'Temp', 'temp', 'temperature', 'air_temperature', 'TAS']
    description: "Air temperature at 2 meters above ground level"
    path: "/net/venus/kenes/downloaded-data/acannon/USask-WRF-WCA/ctl-wrf-wca/T2/*.nc"
    transform: "x - 273.15"

  relative_humidity:

    alternative_names: ["RH", "RH2", "relative_humidity_2m", "RH2M", "rh", "rh2"]
    description: "Relative humidity at 2 meters above ground level"
    path: "/users/rpayne/data/unproc/WRF/ctl/RH/*.nc"
    transform: null

  precipitation:

    alternative_names: ["Precip", "Pr", "total_precipitation", "PREC", "prec", "pr", "rainfall", "Rainfall"]
    description: "Total accumulated precipitation over the past hour"
    path: "/net/venus/kenes/downloaded-data/acannon/USask-WRF-WCA/ctl-wrf-wca/PREC/*.nc"
    transform: null

