settings:

  start_year: 2004
  end_year: 2004
  overwinter: true
  crop_x_index: [110,114] #[110,366]
  crop_y_index: [20,24] #[20,276]
  chunks: "auto"
  parallel: true
  n_cpu_cores: -1
  output_dir: "/users/rpayne/data/unproc/WRF/ctl/FWI/"
  path_to_cffdrs-ng: "/users/rpayne/cffdrs-ng"

FWI_parameters:

  FFMC_default: 85.0
  DMC_default: 6.0
  DC_default: 15.0
  season_consecutive_days: 3
  season_start_temp: 12.0
  season_stop_temp: 5.0

# Note: all data must have identical dimensions, 
# with both latitude and longitude as a coordinate or variable!
data_vars:

  t_dim_name: "time"
  x_dim_name: "rlon"
  y_dim_name: "rlat"

  wind_speed:

    alternative_names: ['WS10', 'WindSpeed', 'WindSpeed10m','WS','ws','ws10']
    description: "Wind speed at 10 meters above ground level"
    path: "/users/rpayne/data/unproc/WRF/ctl/WS10/"
    transform: null

  air_temperature:

    alternative_names: ['T2', 'Temperature', 'T', 'Temp', 'temp', 'temperature', 'air_temperature', 'TAS']
    description: "Air temperature at 2 meters above ground level"
    path: "/net/venus/kenes/downloaded-data/acannon/USask-WRF-WCA/ctl-wrf-wca/T2/"
    transform: "x - 273.15"

  relative_humidity:

    alternative_names: ["RH", "RH2", "relative_humidity_2m", "RH2M", "rh", "rh2"]
    description: "Relative humidity at 2 meters above ground level"
    path: "/users/rpayne/data/unproc/WRF/ctl/RH/"
    transform: null

  precipitation:

    alternative_names: ["Precip", "Pr", "total_precipitation", "PREC", "prec", "pr", "rainfall", "Rainfall"]
    description: "Total accumulated precipitation over the past hour"
    path: "/net/venus/kenes/downloaded-data/acannon/USask-WRF-WCA/ctl-wrf-wca/PREC/"
    transform: null

