settings:

  start_year: 2004
  end_year: 2004
  overwinter: true
  domain_index_x: [110,366]
  domain_index_y: [20,276]
  chunks: "auto"
  parallel: true
  n_cpu_cores: -1
  FFMC_DEFAULT: 85
  DMC_DEFAULT: 6
  DC_DEFAULT: 15
  consecutive_days: 3
  start_temp: 12
  stop_temp: 5
  output_dir: "/users/rpayne/data/unproc/WRF/ctl/FWI/"
  path_to_Ensemble_FWI: "/users/rpayne/Ensemble_FWI"
  path_to_cffdrs-ng: "/users/rpayne/cffdrs-ng"


# Note: all data must be on the same grid and have the same time dimension.
data_vars:

  wind_speed:

    alternative_names: ['WS10', 'WindSpeed', 'WindSpeed10m','WS','ws','ws10']
    description: "Wind speed at 10 meters above ground level"
    path: "/users/rpayne/data/unproc/WRF/ctl/WS10/"
    x_dim_name: "rlon"
    y_dim_name: "rlat"
    t_dim_name: "time"
    transform: null

  air_temperature:

    alternative_names: ['T2', 'Temperature', 'T', 'Temp', 'temp', 'temperature', 'air_temperature', 'TAS']
    description: "Air temperature at 2 meters above ground level"
    path: "/net/venus/kenes/downloaded-data/acannon/USask-WRF-WCA/ctl-wrf-wca/T2/"
    x_dim_name: "rlon"
    y_dim_name: "rlat"
    t_dim_name: "time"
    transform: "x - 273.15"

  relative_humidity:

    alternative_names: ["RH", "RH2", "relative_humidity_2m", "RH2M", "rh", "rh2"]
    description: "Relative humidity at 2 meters above ground level"
    path: "/users/rpayne/data/unproc/WRF/ctl/RH/"
    x_dim_name: "rlon"
    y_dim_name: "rlat"
    t_dim_name: "time"
    transform: null

  precipitation:

    alternative_names: ["Precip", "Pr", "total_precipitation", "PREC", "prec", "pr", "rainfall", "Rainfall"]
    description: "Total accumulated precipitation over the past hour"
    path: "/net/venus/kenes/downloaded-data/acannon/USask-WRF-WCA/ctl-wrf-wca/PREC/"
    x_dim_name: "rlon"
    y_dim_name: "rlat"
    t_dim_name: "time"
    transform: null

