settings:

  year: 2004
  overwinter: true
  domain_index_x: [110,366]
  domain_index_y: [20,276]
  chunks: "auto"
  parallel: true
  n_cpu_cores: -1
  FFMC_DEFAULT: 85
  DMC_DEFAULT: 6
  DC_DEFAULT: 15
  consecutive_days: 3
  start_temp: 12
  stop_temp: 5

data_vars:

  wind_speed:

    alternative_names: ["wind_speed_10m", "WS10"]
    units: "m/s"
    description: "Wind speed at 10 meters above ground level"
    path: "/users/rpayne/data/unproc/WRF/ctl/WS10/"

  air_temperature:

    alternative_names: ["air_temp_2m", "T2", "TAS"]
    units: "K"
    description: "Air temperature at 2 meters above ground level"
    path: "/users/rpayne/data/unproc/WRF/ctl/TAS/"

  relative_humidity:

    alternative_names: ["RH", "RH2", "relative_humidity_2m"]
    units: ""
    description: "Relative humidity at 2 meters above ground level"
    path: "/users/rpayne/data/unproc/WRF/ctl/RH/"

  precipitation:

    alternative_names: ["precipitation_1h", "P1H", "total_precipitation", "PREC", "prec", "pr"]
    units: "mm"
    description: "Total accumulated precipitation over the past hour"
    path: "/users/rpayne/data/unproc/WRF/ctl/PREC/"

